### ISSUE TITLE
 Робота над помилками.

### ISSUE THREAD

**Issue by Alecto** [DmitriyKharchenko1988/grid-template#1]
1)

Ваша робота містить невалідний код (невалідний означає невідповідність стандартам HTML, іншими словами код з критичними помилками).
Усі файли проекту, без винятку, мають проходити валідацію.
HTML validator... https://validator.w3.org/#validate_by_input
  CSS validator... https://jigsaw.w3.org/css-validator/#validate_by_upload

![image](https://github.com/DmitriyKharchenko1988/grid-template/assets/8464662/cb1e96b0-4c0b-4b89-b539-c82422a23d95)

2)
чому дужки поза селектором?
![image](https://github.com/DmitriyKharchenko1988/grid-template/assets/8464662/11fd59d5-9178-44a0-bdd2-6f439bddf553)

3)
У файлах встановлені різні відступи.
Тобто, в якомусь файлі встановлені відступи в 2 пробіли, в іншому файлі відступи становлять 4 пробіли.
Допускається відступи або 2 або 4, кількість відступів повинна бути однаковою для всіх файлів проекту, включаючи HTML, CSS, JS, TS.
Використання символу табуляції, 1/3/5/7 пробілів як відступи - заборонено.
Визначте кількість відступів та налаштуйте їх число для кожного файлу окремо, а також виправте кількість пробілів для нових файлів за замовчуванням.
Як це зробити - описано в документації використовуваного вами редактора (питання гуглиться).
Після настроювання відступів виконайте автоматичне форматування для всіх файлів проекту.

4)
Зовнішній вигляд не відповідає поставленому завданню.
Порівняйте результат із макетом або майстер-шаблоном.

![image](https://github.com/DmitriyKharchenko1988/grid-template/assets/8464662/1f481eb2-19a4-487f-8276-a745ecf77617)

5)
Зовнішній вигляд не відповідає поставленому завданню.
Порівняйте результат із макетом або майстер-шаблоном.

![image](https://github.com/DmitriyKharchenko1988/grid-template/assets/8464662/9e064a9d-f62f-4127-9231-8633d4b8cce9)

**Comment by DmitriyKharchenko1988** [comment]
Исправил валидацию, переделал form,skills.

https://github.com/DmitriyKharchenko1988/grid-template

https://dmitriykharchenko1988.github.io/grid-template/




ср, 19 июл. 2023 г. в 21:10, Andrii Fomenko ***@***.***>:

**Comment by DmitriyKharchenko1988** [comment]
Исправил валидацию, переделал form,skills.

https://github.com/DmitriyKharchenko1988/grid-template

https://dmitriykharchenko1988.github.io/grid-template/

чт, 20 июл. 2023 г. в 20:47, Дмитро ***@***.***>:

**Comment by Alecto** [comment]
виправлено, робота прийнята

Повідомте будь ласка назву (день + час) групи + ваше ім'я прізвище.
У листуванні ця інформація відсутня.

чт, 20 лип. 2023 р. о 20:57 DmitriyKharchenko1988 ***@***.***>
пише:

**Comment by DmitriyKharchenko1988** [comment]
пн\ср 19.00-21.00
Харченко Дмитрий

пт, 21 июл. 2023 г. в 11:53, Andrii Fomenko ***@***.***>:

**Comment by Alecto** [comment]
отметил

пт, 21 лип. 2023 р. о 14:38 DmitriyKharchenko1988 ***@***.***>
пише:
